### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by mrmichael1389** [maeneak/utecio-ha#23]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/maeneak/utecio-ha/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

HACS can’t manage this because there hasn’t been a release. 

### Describe the solution you'd like

Could you do a release so HACS can pull updates?

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by maeneak** [comment]
I've created a release for testing with HACS. I haven't had a chance to test it. Let me know if there's any problems importing.

**Comment by mrmichael1389** [comment]
<Integration maeneak/utecio-ha> Failed to download https://github.com/maeneak/utecio-ha/releases/download/main/ultraloq_ble.zip

For some reason HACS still shows no releases and fails to download. I’m guessing it has something to do with it being marked a pre-release. On the GitHub page it should show the release version I think.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by maeneak** [comment]
Try again I've removed the requirement for using a release. Should just clone the repo now 👍

**Comment by mrmichael1389** [comment]
That did it. It can now be installed through HACS. Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
